# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SkillLoop < Formula
  desc "An agentic skill orchestrator powered by Claude Code"
  homepage "https://github.com/takumiyoshikawa/skill-loop"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/takumiyoshikawa/skill-loop/releases/download/v0.1.0/skill-loop_0.1.0_darwin_amd64.tar.gz"
      sha256 "44d3f957d6f1b5ced621a8d1009270a74303af247adf38632ce3a81809d691b1"

      def install
        bin.install "skill-loop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/takumiyoshikawa/skill-loop/releases/download/v0.1.0/skill-loop_0.1.0_darwin_arm64.tar.gz"
      sha256 "7ad3d68607fa1180824c5b1f0bf84249a99f6900b170826deea42d526593f66c"

      def install
        bin.install "skill-loop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/takumiyoshikawa/skill-loop/releases/download/v0.1.0/skill-loop_0.1.0_linux_amd64.tar.gz"
      sha256 "e6f3d3beeddf36d3b76cb4e8c08fc8c8bfeaaebf6d727e530cb3e6151559b59e"
      def install
        bin.install "skill-loop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/takumiyoshikawa/skill-loop/releases/download/v0.1.0/skill-loop_0.1.0_linux_arm64.tar.gz"
      sha256 "8c3ed186cda29b8dfb2170ac5cbcb7323c83501cacfe34bc3daeb82b6c40d4fe"
      def install
        bin.install "skill-loop"
      end
    end
  end
end
